## 講習2 --- Numpyの基本 

Numpyは、数値計算を効率よく処理するためのサードパーティモジュールです。  特に、多次元配列を取り扱う際に処理速度が速くなり、コードの表記も効率的になります。
pythonの標準の配列であるリスト型では処理が遅いため、科学計算ではNumpyのndarrayという多次元配列のデータ型を使います。Numpyはサードパーティモジュールですが、科学計算では標準的に使われます。このあと紹介するpyfitおよびmatplotlibでも、このndarrayを採用しています。  

以下、ndarrayの基本について説明し、numpyの基本的で使える関数について説明します。 

### リスト型 
まずはpythonの標準のリスト型を見てみましょう。


In [1]:
a = [1, 2, 3, 4]
b = [10, 20, 30, 40]

\+ 演算子はリストとリストの結合になります。\* 演算子はリストの繰り返しを作成します。

In [2]:
a + b

[1, 2, 3, 4, 10, 20, 30, 40]

In [3]:
a * 4

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

ベクトル的に演算したい場合には、下のように、forループを回して各要素を取り出してから演算をする必要があります。

In [4]:
n = len(a)
c = [0] * n
for i in range(n):
    c[i] = a[i] + b[i]
c

[11, 22, 33, 44]

In [5]:
print (c)

[11, 22, 33, 44]


### numpyのndarray    
numpyではもっとすっきりした処理、ベクトル処理、ができます。処理速度も速いです。

In [6]:
import numpy as np   #  一般的に np と省略される

numpy.array() 関数を使って、pythonのリストをndarray に変換します。

In [7]:
an = np.array(a)  
bn = np.array(b)

In [8]:
cn = an + bn
cn

array([11, 22, 33, 44])

In [9]:
print (cn)

[11 22 33 44]


In [10]:
an * 4

array([ 4,  8, 12, 16])

### numpyの関数   
numpyで用意されている関数は数多くあります。 cellの中で、np.とタイプしてタブキーを押すと候補が表示されます。あるいはnp.mでタブキーを押すとmで始まる関数の候補が表示されます。

In [11]:
np.max(cn), np.min(cn), np.mean(cn)

(44, 11, 27.5)

#### numpy.where()    
天文のデータ処理では(でなくても?)次の numpy.where( ) が便利です。 バッドマスク処理や外れ値の除外に使えます。

In [12]:
dn = np.array([1, 1, 3, 1, 1])

**np.where( )** 関数は、( )内の条件を満たす要素のindexを返します。 下の例では、2以上の値をとる要素に-99を代入するという意味です。

In [13]:
dn[np.where(dn > 2)] = -99   

In [14]:
dn

array([  1,   1, -99,   1,   1])

#### numpy.zeros( )   
下のように、**numpy.zeros( )** を使って、全要素が0の5 x 5 の二次元配列を作成することができます。  

In [15]:
data = np.zeros((5, 5))

In [16]:
data

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [17]:
data[0, 1] = 2   #   [0, 1]の要素に2を代入する。  

numpyに限らず、pythonではindexは0から始まります。C言語と同じです。

In [18]:
data

array([[ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

このdataの表示を見て気づいたかとも思いますが、
左下を原点とした二次元画像としたときに、ndarrayでは **(y, x)**のように xとyのindexを逆にして要素が格納されます。
後で、pyfitsのところでも再び触れます。

### 配列について補足  
Pythonの配列には、**リスト**と**タプル**があります。  
**リスト**は [ ] で囲まれ変更可能なオブジェクトです。  
**タプル**は( ) で囲まれ変更不可能なオブジェクトです。


In [19]:
aa = [1, 2, 3, 4]

In [20]:
aa[2] = 10

In [21]:
aa

[1, 2, 10, 4]

In [22]:
bb = (10, 20, 30, 40)

In [23]:
bb

(10, 20, 30, 40)

In [24]:
bb[2] = 100

TypeError: 'tuple' object does not support item assignment

怒られました。    

numpyのndarrayは上のリストやタプルと違い、オブジェクトを表示させた場合に　**array([ ])**となります。   
jupyter notebookで print ([オブジェクト]) とするとそのオブジェクトの中身が表示されますが、上見てきたように、
[オブジェクト]　だけで shift+enter すると オブジェクトを表示することができるのです。
